In [12]:
!pip install ucimlrepo
from ucimlrepo import fetch_ucirepo

# fetch dataset
wine = fetch_ucirepo(id=109)

# data (as pandas dataframes)
X = wine.data.features
y = wine.data.targets

# metadata
print(wine.metadata)

# variable information
print(wine.variables)

Requirement already satisfied: ucimlrepo in /usr/local/lib/python3.10/dist-packages (0.0.2)
{'uci_id': 109, 'name': 'Wine', 'repository_url': 'https://archive.ics.uci.edu/dataset/109/wine', 'data_url': 'https://archive.ics.uci.edu/static/public/109/data.csv', 'abstract': 'Using chemical analysis to determine the origin of wines', 'area': 'Physical Science', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 178, 'num_features': 13, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1992, 'last_updated': 'Mon Aug 28 2023', 'dataset_doi': '10.24432/C5PC7J', 'creators': ['Stefan Aeberhard', 'M. Forina'], 'intro_paper': {'title': 'Comparative analysis of statistical pattern recognition methods in high dimensional settings', 'authors': 'S. Aeberhard, D. Coomans, O. Vel', 'published_in': 'Pattern Recognition', 'year': 1994, 'url': 'https://www.semanticscholar.org/paper/83dc3e4030d7b9fbdbb4bde03ce12ab70ca10528', 'doi': '10.1016/0031-3203(94)90145-7'}, 'additional_info': {'summary': 'These data are the results of a chemical analysis of wines grown in the same region in Italy but derived from three different cultivars. The analysis determined the quantities of 13 constituents found in each of the three types of wines. \r\n\r\nI think that the initial data set had around 30 variables, but for some reason I only have the 13 dimensional version. I had a list of what the 30 or so variables were, but a.)  I lost it, and b.), I would not know which 13 variables are included in the set.\r\n\r\nThe attributes are (dontated by Riccardo Leardi, riclea@anchem.unige.it )\r\n1) Alcohol\r\n2) Malic acid\r\n3) Ash\r\n4) Alcalinity of ash  \r\n5) Magnesium\r\n6) Total phenols\r\n7) Flavanoids\r\n8) Nonflavanoid phenols\r\n9) Proanthocyanins\r\n10)Color intensity\r\n11)Hue\r\n12)OD280/OD315 of diluted wines\r\n13)Proline \r\n\r\nIn a classification context, this is a well posed problem with "well behaved" class structures. A good data set for first testing of a new classifier, but not very challenging.           ', 'purpose': 'test', 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'All attributes are continuous\r\n\t\r\nNo statistics available, but suggest to standardise variables for certain uses (e.g. for us with classifiers which are NOT scale invariant)\r\n\r\nNOTE: 1st attribute is class identifier (1-3)', 'citation': None}}
                            name     role         type demographic  \
0                          class   Target  Categorical        None
1                        Alcohol  Feature   Continuous        None
2                      Malicacid  Feature   Continuous        None
3                            Ash  Feature   Continuous        None
4              Alcalinity_of_ash  Feature   Continuous        None
5                      Magnesium  Feature      Integer        None
6                  Total_phenols  Feature   Continuous        None
7                     Flavanoids  Feature   Continuous        None
8           Nonflavanoid_phenols  Feature   Continuous        None
9                Proanthocyanins  Feature   Continuous        None
10               Color_intensity  Feature   Continuous        None
11                           Hue  Feature   Continuous        None
12  0D280_0D315_of_diluted_wines  Feature   Continuous        None
13                       Proline  Feature      Integer        None

   description units missing_values
0         None  None             no
1         None  None             no
2         None  None             no
3         None  None             no
4         None  None             no
5         None  None             no
6         None  None             no
7         None  None             no
8         None  None             no
9         None  None             no
10        None  None             no
11        None  None             no
12        None  None             no
13        None  None             no

In [17]:
X

,Alcohol,Malicacid,Ash,Alcalinity_of_ash,Magnesium,Total_phenols,Flavanoids,Nonflavanoid_phenols,Proanthocyanins,Color_intensity,Hue,0D280_0D315_of_diluted_wines,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [11]:
input_var = X
target_var = y

In [ ]:
sns.scatterplot(x='sepal_length',
y='sepal_width',
hue='species', # species의 종류에 따라 색깔 구분
style='species', # species의 종류에 따라 점(markers, points)의 형태 구분
s=100, # 점의 크기 지정
data=iris)
plt.show()

In [24]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X)
input_scaled = ss.transform(X)
print(input_scaled[0:5,])

[[ 1.01428247  1.64083119]
 [ 0.9650412  -0.40957298]
 [ 1.39475632 -0.49909529]
 [ 2.33458583  0.01471403]
 [-0.03684263  1.41163108]]

In [25]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(input_scaled)
wine_pca = pca.transform(input_scaled)
print(wine_pca.shape)
print(wine_pca[0:6,])

(178, 2)
[[ 1.01428247  1.64083119]
 [ 0.9650412  -0.40957298]
 [ 1.39475632 -0.49909529]
 [ 2.33458583  0.01471403]
 [-0.03684263  1.41163108]
 [ 2.23903942 -0.02535888]]

In [27]:
import pandas as pd
wine_pca=pd.DataFrame(wine_pca,columns=['pc1','pc2'])
print(wine_pca)

          pc1       pc2
0    1.014282  1.640831
1    0.965041 -0.409573
2    1.394756 -0.499095
3    2.334586  0.014714
4   -0.036843  1.411631
..        ...       ...
173 -0.022225 -0.346696
174  0.009971  0.178282
175  0.281644  1.433488
176  0.297558  1.425436
177 -0.595214 -0.016287

[178 rows x 2 columns]

In [28]:
print(pca.explained_variance_ratio_)
import numpy as np
print(np.sum(pca.explained_variance_ratio_))

[0.5 0.5]
1.0

In [34]:
pca_all = PCA(n_components=2)
pca_all.fit(input_scaled)
wine_pca_all = pca_all.transform(input_scaled)
print(wine_pca_all.shape)
print(wine_pca_all[0:6,])
print(pca_all.explained_variance_ratio_)
print(np.sum(pca_all.explained_variance_ratio_))

(178, 2)
[[ 1.01428247  1.64083119]
 [ 0.9650412  -0.40957298]
 [ 1.39475632 -0.49909529]
 [ 2.33458583  0.01471403]
 [-0.03684263  1.41163108]
 [ 2.23903942 -0.02535888]]
[0.5 0.5]
1.0

In [35]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import decomposition
from sklearn import datasets
from sklearn.preprocessing import scale

pca = decomposition.PCA(n_components=2)
X = pca.fit_transform(X)
loadings = pd.DataFrame(pca.components_.T, columns=['PC1', 'PC2'], index=wine.data.feature_names)
loadings

   PC1  PC2
0  1.0  0.0
1  0.0  1.0

In [20]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import decomposition
from sklearn import datasets
from sklearn.preprocessing import scale

pca = decomposition.PCA(n_components=2)
X = pca.fit_transform(X)
loadings = pd.DataFrame(pca.components_.T, columns=['PC1', 'PC2'], index=wine.data.feature_names)
loadings

   PC1  PC2
0  1.0  0.0
1  0.0  1.0