In [6]:
import pandas as pd
url="https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data"
AB=pd.read_csv(url, header=None, names=['Sex','Length','Diameter','Height','Whole','Shucked','Viscera','Shell','Rings'])
print(AB.head())

  Sex  Length  Diameter  Height   Whole  Shucked  Viscera  Shell  Rings
0   M   0.455     0.365   0.095  0.5140   0.2245   0.1010  0.150     15
1   M   0.350     0.265   0.090  0.2255   0.0995   0.0485  0.070      7
2   F   0.530     0.420   0.135  0.6770   0.2565   0.1415  0.210      9
3   M   0.440     0.365   0.125  0.5160   0.2155   0.1140  0.155     10
4   I   0.330     0.255   0.080  0.2050   0.0895   0.0395  0.055      7

In [7]:
AB.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Sex       4177 non-null   object
 1   Length    4177 non-null   float64
 2   Diameter  4177 non-null   float64
 3   Height    4177 non-null   float64
 4   Whole     4177 non-null   float64
 5   Shucked   4177 non-null   float64
 6   Viscera   4177 non-null   float64
 7   Shell     4177 non-null   float64
 8   Rings     4177 non-null   int64
dtypes: float64(7), int64(1), object(1)
memory usage: 293.8+ KB

In [9]:
AB.describe()

,Length,Diameter,Height,Whole,Shucked,Viscera,Shell,Rings
count,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000
mean,0.523992,0.407881,0.139516,0.828742,0.359367,0.180594,0.238831,9.933684
std,0.120093,0.099240,0.041827,0.490389,0.221963,0.109614,0.139203,3.224169
min,0.075000,0.055000,0.000000,0.002000,0.001000,0.000500,0.001500,1.000000
25%,0.450000,0.350000,0.115000,0.441500,0.186000,0.093500,0.130000,8.000000
50%,0.545000,0.425000,0.140000,0.799500,0.336000,0.171000,0.234000,9.000000
75%,0.615000,0.480000,0.165000,1.153000,0.502000,0.253000,0.329000,11.000000
max,0.815000,0.650000,1.130000,2.825500,1.488000,0.760000,1.005000,29.000000

In [10]:
AB[['Length','Height']]

      Length  Height
0      0.455   0.095
1      0.350   0.090
2      0.530   0.135
3      0.440   0.125
4      0.330   0.080
...      ...     ...
4172   0.565   0.165
4173   0.590   0.135
4174   0.600   0.205
4175   0.625   0.150
4176   0.710   0.195

[4177 rows x 2 columns]

In [13]:
AB_data=AB.drop(['Sex'],axis=1)
print(AB_data)

      Length  Diameter  Height   Whole  Shucked  Viscera   Shell  Rings
0      0.455     0.365   0.095  0.5140   0.2245   0.1010  0.1500     15
1      0.350     0.265   0.090  0.2255   0.0995   0.0485  0.0700      7
2      0.530     0.420   0.135  0.6770   0.2565   0.1415  0.2100      9
3      0.440     0.365   0.125  0.5160   0.2155   0.1140  0.1550     10
4      0.330     0.255   0.080  0.2050   0.0895   0.0395  0.0550      7
...      ...       ...     ...     ...      ...      ...     ...    ...
4172   0.565     0.450   0.165  0.8870   0.3700   0.2390  0.2490     11
4173   0.590     0.440   0.135  0.9660   0.4390   0.2145  0.2605     10
4174   0.600     0.475   0.205  1.1760   0.5255   0.2875  0.3080      9
4175   0.625     0.485   0.150  1.0945   0.5310   0.2610  0.2960     10
4176   0.710     0.555   0.195  1.9485   0.9455   0.3765  0.4950     12

[4177 rows x 8 columns]

In [19]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
X=AB[['Length','Height']]
y=AB['Sex']
train_input, test_input, train_target, test_target = train_test_split(
    X,y, test_size=0.25,random_state=1004)
k_nn = KNeighborsClassifier()
k_nn.fit(train_input, train_target)
print(k_nn.score(train_input, train_target))
print(k_nn.score(test_input, test_target))

0.6302681992337165
0.48995215311004786

In [38]:
AB_data=AB.drop(['Sex'],axis=1)
AB_data

      Length  Diameter  Height   Whole  Shucked  Viscera   Shell  Rings
0      0.455     0.365   0.095  0.5140   0.2245   0.1010  0.1500     15
1      0.350     0.265   0.090  0.2255   0.0995   0.0485  0.0700      7
2      0.530     0.420   0.135  0.6770   0.2565   0.1415  0.2100      9
3      0.440     0.365   0.125  0.5160   0.2155   0.1140  0.1550     10
4      0.330     0.255   0.080  0.2050   0.0895   0.0395  0.0550      7
...      ...       ...     ...     ...      ...      ...     ...    ...
4172   0.565     0.450   0.165  0.8870   0.3700   0.2390  0.2490     11
4173   0.590     0.440   0.135  0.9660   0.4390   0.2145  0.2605     10
4174   0.600     0.475   0.205  1.1760   0.5255   0.2875  0.3080      9
4175   0.625     0.485   0.150  1.0945   0.5310   0.2610  0.2960     10
4176   0.710     0.555   0.195  1.9485   0.9455   0.3765  0.4950     12

[4177 rows x 8 columns]

In [39]:
input_var = AB_data[['Length','Diameter','Height','Whole',
  'Shucked','Viscera','Shell','Rings']]
target_var = AB['Sex']
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(input_var)
input_scaled=ss.transform(input_var)

In [66]:
from sklearn.decomposition import PCA
import numpy as np
for k in range(0, 9):
  pca = PCA(n_components = k)
  pca.fit(input_scaled)
  adult_pca = pca.transform(input_scaled)
  if np.sum(np.sum(pca.explained_variance_ratio_)) > 0.95:
    print(adult_pca.shape)
    print(pca.explained_variance_ratio_)
    print("K=",k,":",np.sum(pca.explained_variance_ratio_))

(4177, 3)
[0.83905489 0.08695162 0.03230539]
K= 3 : 0.9583119047723673
(4177, 4)
[0.83905489 0.08695162 0.03230539 0.02074873]
K= 4 : 0.9790606351413722
(4177, 5)
[0.83905489 0.08695162 0.03230539 0.02074873 0.01061871]
K= 5 : 0.98967934310019
(4177, 6)
[0.83905489 0.08695162 0.03230539 0.02074873 0.01061871 0.0079341 ]
K= 6 : 0.9976134389627903
(4177, 7)
[0.83905489 0.08695162 0.03230539 0.02074873 0.01061871 0.0079341
 0.00158677]
K= 7 : 0.9992002094437769
(4177, 8)
[8.39054894e-01 8.69516209e-02 3.23053901e-02 2.07487304e-02
 1.06187080e-02 7.93409586e-03 1.58677048e-03 7.99790556e-04]
K= 8 : 1.0

In [65]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples, silhouette_score
for k in range(2,11):
  kmeans = KMeans(n_clusters=k, init='k-means++', max_iter=300,random_state=45982)
  kmeans.fit(input_var)
  #print(kmeans.labels_)
  S=silhouette_score(input_var,kmeans.labels_)
  print("K=",k,":",S)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

K= 2 : 0.5288184185254473

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

K= 3 : 0.503143036330113

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

K= 4 : 0.5054535790979167

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

K= 5 : 0.49455469664821006

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

K= 6 : 0.49699482219361013

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

K= 7 : 0.4884200419864701

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

K= 8 : 0.47451697889675754

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

K= 9 : 0.5047168718855812

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

K= 10 : 0.5023191809002332